### ISSUE TITLE
`.bufferBy` should emit empty array if buffer is empty (now just don't emit)

### ISSUE THREAD

**Issue by rpominov** [rpominov/kefir#108]
For consistency, and for the cases like https://gitter.im/pozadi/kefir?at=5571f18227d2203776ccc293

**Comment by rpominov** [comment]
Not sure if it a breaking change or a bug fix. I prefer latter.

**Comment by shamansir** [comment]
Great, thank you!

**Comment by rpominov** [comment]
For those who by chance was affected by the fix in a bad way, you should add `.filter(arr => arr.length > 0)` after `.bufferBy()`.

@shamansir No problem!
