### ISSUE TITLE
React onClick best practices

### ISSUE THREAD

**Issue by bcoop713** [rpominov/kefir#110]
I'm using kefir with a new react app I'm working on, and I'm trying to find the best way to handle the onClick events.

I've read all the other issues on here about alternatives to Bus, and I settled on using 

    var count = Kefir.pool();
    clickHandler = count.plug(Kefir.constant(1)); 

But I don't see how this is different from the bus of doom situation.
Is there a better way of handling React events?

Thanks,

**Comment by rpominov** [comment]
You are right, it's not much different from using emitter. But with the interface that React provides for subscribing to events, you have to use something like emitter.

See also https://gitter.im/pozadi/kefir?at=55782a6ff40a067d1c9c0cf9
