### ISSUE TITLE
Explode one event into zero or more

### ISSUE THREAD

**Issue by Twisol** [rpominov/kefir#111]
I've found the following pattern fairly useful in one of my current projects. It allows you to transform one event into multiple (or none). Does anything like this exist currently in Kefir? I see that a map+flatten combo would work in the example below, but in my use-case it isn't immediately natural to collect results as an array.

```javascript
Kefir.Stream.prototype.explode = function(fn) {
  return this.withHandler(function(emitter, ev) {
    if (ev.type === "end") {
      emitter.end();
    } else if (ev.type === "value") {
      fn(emitter, ev.value);
    }
  });
};
```

Usage:
```javascript
var things$ = Kefir.sequentially(100, ["abc\ndef", "ghi\njkl\nmno"]);
var lines$ = things$.explode(function(emitter, value) {
  value.split("\n").forEach(function(line) {
    emitter.emit(line);
  });
});
```

**Comment by rpominov** [comment]
You're probably looking for [flatMap](http://rpominov.github.io/kefir/#flat-map)

**Comment by Twisol** [comment]
Missed that somehow. Thanks!

**Comment by rpominov** [comment]
Or in this case probably flatten is better:

```js
var things$ = Kefir.sequentially(100, ["abc\ndef", "ghi\njkl\nmno"]);
var lines$ = things$.flatten(function(value) {
  return value.split("\n");
});
```

Note that it also accepts a transformer function.
