### ISSUE TITLE
skipDuplicates and object reference

### ISSUE THREAD

**Issue by appedemic** [rpominov/kefir#117]
When I have a stream with an object that is manipulated in a map function, skipDuplicates doesn't detect the changes because both the previous and current value (that will be compared) are pointing to the same object.

```
let obj = {x: { z: 0} };
Kefir
  .fromPoll(1000, () => { obj.x.z = n++; return obj; })
  .map(v => v.x)
  .log()
```
This logs 0, 1, 2, 3, ....

But this:
```
Kefir
  .fromPoll(1000, () => { obj.x.z = n++; return obj; })
  .map(v => v.x)
  .skipDuplicates()
  .log()
```
only logs 0

When using a custom comparator within the skipDuplicates, the two values point to the same object:

```
Kefir
  .fromPoll(1000, () => { obj.x.z = n++; return obj; })
  .map(v => v.x)
  .skipDuplicates((a,b) => {
    assert(a === b);
  })
  .log()
```

The only way to make it work is to explicitly map to a fresh object:
```
Kefir
  .fromPoll(1000, () => { obj.x.z = n++; return obj; })
  .map(
    v => Object.assign({}, v.x)
  )
  .skipDuplicates()
  .log()
```

Is this the intended behaviour when streaming and mapping an object? Should I ensure that map always returns a duplicate?

**Comment by rpominov** [comment]
Not sure if it's the issue, but it seems that you always return `undefined` from your custom comparator function.

**Comment by rpominov** [comment]
If I understand correctly, you should do something like this:

```js
Kefir
  .fromPoll(1000, () => { obj.x.z = n++; return obj; })
  .map(v => v.x)
  .skipDuplicates((a, b) => {
    return a.z === b.z;
  })
  .log()
```

But anyway, I'd recommend to transfer only immutable objects over Kefir wires :)

**Comment by appedemic** [comment]
Not the issue, the custom compare function is to illustrate both a and b refer to the same object. The comparator function I use is R.equals from ramda which deep checks the object properties for equality.

The problem/misunderstanding I had was that I assumed the .map(v => v.x) would create a new object from obj.x but it returns a reference to a part of the original obj. So later on, when obj gets manipulated elsewhere, the mapped value will point to the manipulated part of obj.

Anyway, right now I make sure I map to a deep copy and it works fine. My solution ends up to be
```
Kefir
  .fromPoll(1000, () => { obj.x.z = n++; return obj; })
  .map(R.clone(R.path(['x'])))
  .skipDuplicates(R.equals)
  .log()
```

**Comment by rpominov** [comment]
Ah, right, you was always referencing the same object that was updated globally, so `a.z === b.z` is always `true` as `a` and `b` are references to the same object.

Nothing can be done here on Kefir side, and cloning is a correct fix.
