### ISSUE TITLE
add kefir to cdnjs

### ISSUE THREAD

**Issue by safareli** [rpominov/kefir#118]
it will be great if you add kefir to [cdnjs](https://github.com/cdnjs/cdnjs)

**Comment by rpominov** [comment]
I've added it to [jsdelivr](https://github.com/jsdelivr/jsdelivr/tree/master/files/kefir), have no idea when it appears on the actual CDN though :smile:

**Comment by rpominov** [comment]
Ah, it's up actually:

http://cdn.jsdelivr.net/kefir/2.7.1/kefir.js
http://cdn.jsdelivr.net/kefir/2.7.1/kefir.min.js

If anyone wants to add Kefir to cdnjs, please do. I guess it can be done by not an owner of the repo.
