### ISSUE TITLE
how to eliminate dead code

### ISSUE THREAD

**Issue by nostalgicdodo** [rpominov/kefir#121]
I ran uglifyjs (via webpack) on my code but the entire lib still got bundled. Is there a specific approach to doing this?

**Comment by rpominov** [comment]
Not sure what you mean. Could you explain what you've expected to happen? May be an example of how dead code elimination works for some other lib?

**Comment by nostalgicdodo** [comment]
Apologies if I sound naive. This is my first time attempting dead code elimination. Based on [this](https://github.com/xjamundx/dead-code#dead-code) I was under the impression that if say I used only the `sequentially` and `log` functions, or if I did something like this,
```js
var kefir = {
	sequentially: require ( "kefir" ).sequentially,
	log: require ( "kefir" ).log
};
```
then uglifyjs would prune out the rest and the build file would only consist of these two functions.

Am I incorrect in this assumption?

**Comment by rpominov** [comment]
No, uglifyjs isn't that smart. It can detect only simple dead code cases like `if (1 === 2) { foo(); }`. The link you mentioned said "It looks like uglify won't magically remove the bloat of lodash.", so it doesn't work for lodash either, as expected.

**Comment by rpominov** [comment]
Ah, I see, they require single function from lodash in the `test2.js`:

```js
var isEqual = require('lodash.isequal');
isEqual('a', 'b');
```

(actually separate npm package that contains only that function, but with lodash it also possible to require a sinle function from a main package)

Yeah, we can make this possible potentially, some work already have been done (see #84). But currently it not possible. It'll also require different style of code from programmer, you won't be able to use chaining (`foo.filter(..).map(..)`), will have to require all methods separately, etc.

**Comment by nostalgicdodo** [comment]
I managed to create a custom build. Thanks a bunch!
