### ISSUE TITLE
delegate(); proposed observer-modification for witholding events/transforming to any type

### ISSUE THREAD

**Issue by cefn** [rpominov/kefir#133]
I've struggled to find the equivalent to map(), but where it's feasible to omit a value from the downstream, dispatch an error into the downstream or end it. It may be that there's a way to make map() or some other method() do this, but I can't find any documentation about it.

I find I often am doing a map() then a filter() for example, where both are duplicating the same unmarshalling work, but one is modifying the events, and the other is witholding selected events, which seems messy. In neither case can you introduce an error or an end. An alternative is to create a Kefir.stream(...) as described below but this is also quite messy for what I would expect is a common sort of operation.

Have I overlooked an obvious way to do this using a minimal transform from the api?  Here's some pseudo-code for what I intend...

```javascript
var modifiedStream = Kefir.fromEvents(nodeServer, "eventType").delegate(function(value, emitter){
    var type = typeof value; 
    if(type==="string"){
        emitter.emit(value);
    }
    else if(value===null){
        emitter.end();
    }
    else{
        emitter.error("Unexpected type: " + type);
    }
});
```

It might turn out more or less the same as the following from a behaviour/implementation point of view.

```javascript
var sourceStream = Kefir.fromEvents(nodeServer, "eventType");
var modifiedStream = Kefir.stream(function(emitter){
    var handler, unsubscribe;

    handler = function(value){
        var type = typeof value; 
        if(type==="string"){
            emitter.emit(value);
        }
        else if(value===null){
            emitter.end();
        }
        else{
            emitter.error("Unexpected type: " + type);
        }
    };
    
    unsubscribe = function(){
        if(unsubscribe !== null){
            unsubscribe = null;
            sourceStream.offValue(handler);
        }
    };

    sourceStream.onValue(handler);

    sourceStream.onEnd(unsubscribe);

    return unsubscribe;

})
```

Having an API implementation of this would avoid some closures and unnecessary name-pollution for what would otherwise be an anonymous source stream with a transparently-subscribed and unsubscribed handler. For many simpler cases it would be significantly more terse.

Having an API implementation would also ensure sufficiently smart intervention for triggering unsubscription from the source stream in case of the modified stream sending an end (I don't know if unsubscribe is automatically triggered in this case and unsubscription would certainly be needed here to prevent memory leaks, hence the nasty hack to prevent double unsubscription).

**Comment by rpominov** [comment]
Hey!

Didn't look closely yet, but maybe [.withHandler](http://rpominov.github.io/kefir/#with-handler) is what you need? Except it pushes all events to the handler (not only `values`, but also `errors` and `end`).

**Comment by rpominov** [comment]
Another approach is to use .takeWhile + .flatMap:

```js
var modifiedStream = Kefir.fromEvents(nodeServer, "eventType")
.takeWhile(function(value){
  return value !== null;
})
.flatMap(function(value){
    var type = typeof value; 
    if(type==="string"){
        return Kefir.constant(value);
    }
    return Kefir.constantError("Unexpected type: " + type);
});
```

I'd probably do it this way.

**Comment by cefn** [comment]
I haven't yet used withHandler, so that's a very useful pointer and pretty close to what I want from a callback point of view so thanks for the suggestion.

I am guessing this eliminates the complexity of having to manage unsubscription (e.g. source unsubscription is automatic when an emitter.end() is sent downstream?).

However perhaps more importantly for every case I've needed it so far, it's an onValue which I want to respond to, so I fear withHandler is going to have a lot of unmarshalling in the handler function which will be verbose and error prone if I have to reimplement this every time.

If I was to use withHandler to achieve the API signature and minimal object allocation I was hoping for without embedding it in the handler function, I'd need a filter() to eliminate any **error** or **end**, as well as a map() to unmarshall values from the onAny format to get to the the API simplicity of the 'delegate' pseudo-code I shared, which (perhaps not surprisingly) exactly the problem I started with.

I wondered about using flatMap in the way you showed, but I was concerned about the allocation overhead, hence the interest in an API-native routing through a minimal handler function which is triggered only on values.

"delegate" is a terrible name, perhaps ***withValueHandler(emitter, value)*** captures better what I was hoping for, suggesting that an **error** or **end** from the source stream is passed through untouched by the transform? Going down that route, it would be feasible to have a **withErrorHandler(emitter, value)** and a **withEndHandler(emitter, value)** for symmetry.

I appreciate the implementation you've shared for the case I mentioned, but it was more of an illustration of the kind of signature I aspire to than a real case. It's good to see elegant answers like this as it helps me reflect on my own use of Kefir.

In the short term I think I might follow this flatMap() and .constantX() strategy as you showed. It's better than my current alternative, is terse and functional, and I think covers the immediate cases I need, although I feel the withValueHandler approach is likely to be more efficient and powerful for a number of cases (e.g. marshalling more than one event arising from a single source event possibly embedded in different logic blocks is a challenge through flatMap).

**Comment by rpominov** [comment]
> source unsubscription is automatic when an emitter.end() is sent downstream?

Yeah, it automatic in .withHandler, and more general when a stream ends it always unsubscribes from all sources.

> I wondered about using flatMap in the way you showed, but I was concerned about the allocation overhead

I wouldn't worry about that. Kefir is very optimized for `.flatMap(x => Kefir.constat*(...))` pattern, it almost as fast as `.map(f)` (about ~1.5 times slower according to the benchmark).

> I appreciate the implementation you've shared for the case I mentioned, but it was more of an illustration of the kind of signature I aspire to than a real case.

Right, but we need real cases when such method would be useful to consider adding it.

I also more like flatMap-like solutions for this kind of problems, because they are closer to declarative/functional style, while withHandler / delegate / manual calling emitter methods from an onValue callback — is more imperative. I think this stuff should be like the last resort, when flatMap and others doesn't work.
