### ISSUE TITLE
Deprecate .awaiting?

### ISSUE THREAD

**Issue by rpominov** [rpominov/kefir#145]
If you think of it, `a.awaiting(b)` is just `Kefir.merge([a.map(() => true), b.map(() => false)])`, so it's not a big deal to do ad-hoc. Also notice that it completely discards values from `a` and `b` replacing them with booleans, but often we need those values, for instance:

```js
var streamOfSearchResuts = streamOfSearchQueryChanges.flatMapLatest(sendQueryToServer)
var html = Kefir.merge([
  streamOfSearchQueryChanges.map(() => "loading ..."),
  streamOfSearchResuts.map(result => resultToString(result))
])

// see full example http://jsfiddle.net/fwo0toLx/6/
```

Honestly I've never used .awaiting myself.

## Migration

**Before**

```js
foo.awaiting(bar)
```

**After**

```js
// Strict equivalent
Kefir.merge([foo.map(() => true), bar.map(() => false)])
  .skipDuplicates()
  .toProperty(() => false)

// Loose equivalent
Kefir.merge([foo.map(() => true), bar.map(() => false)])

// More useful equivalent
Kefir.merge([
  foo.map(() => "something more useful than bool"), 
  bar.map(() => "something more useful than bool")
])
```

**Comment by shamansir** [comment]
Just to mention, I am using `.awaiting` as a limit for `filterBy`:

```javascript
Kefir.fromEvents(..., 'click')
     .map(stopPropogation)
     .filterBy(outletClicks.awaiting(someProcessInProgress))
     .map(extractPos)...
```

**Comment by rpominov** [comment]
@shamansir I usually do the following in a situation like this:

```js
const clicks = Kefir.fromEvents(..., 'click').map(stopPropagation)
outerClicks.flatMap(() => clicks.takeUntilBy(someProcessInProgress)).map(extractPos)...
```

**Comment by rpominov** [comment]
@shamansir Oh, and btw, your example may work differently after/if we fix https://github.com/rpominov/kefir/issues/167 (stopPropagation side effect will be called only when filterBy holds true. I.e. filterBy+awaiting will work exactly like flatMap+takeUntilBy work now.)

**Comment by shamansir** [comment]
Got it, thanks! Seems I should update my code again :).

And yeah, looks like #167 is a right decision.
