### ISSUE TITLE
Documentation is invisible

### ISSUE THREAD

**Issue by hallettj** [rpominov/kefir#153]
This might just be something wrong with my computer; but I have reproduced the issue in the Linux versions of Firefox and Chrome.

On http://rpominov.github.io/kefir/ I can see code examples, but no other text is visible. The problem is that my browser does not display the Fira Sans font correctly - but for some reason does not use any of the fallback fonts either.

The code examples do display correctly using Fira Mono.

Looking at network requests, it appears that my browser does download both Fira Sans and Fira Mono.

**Comment by rpominov** [comment]
Related: https://github.com/google/fonts/issues/10
I'll try to figure something out later this week.

**Comment by rpominov** [comment]
We now use mozilla's CDN, could you check if it helps?

**Comment by hallettj** [comment]
Yes, that is much better!

**Comment by rpominov** [comment]
Great! And thanks for the find, btw.
