### ISSUE TITLE
API usage enabling toPromise to reject on timeout? 

### ISSUE THREAD

**Issue by cefn** [rpominov/kefir#156]
I have been puzzling through Promises and unsubscription in my use case a little further while working through the use case which motivated https://github.com/rpominov/kefir/issues/137 and I think I've hit an issue with the expressiveness of the current API.

I need to be able to create a Promise which calls ```resolve()``` if a next value is emitted, or ```reject()``` in case an end or error is emitted or a timeout is hit. This seems pretty mainstream, but I'm struggling to express it through the existing Kefir API. It's possible there's a plain answer, but I can't pick it out and it might suggest some extra feature needed to close the gap.

I need to unsubscribe for resource efficiency where either...
* resolve or reject is called - e.g. the Promise completes in response to a Value or Error event from the source stream. In both of these cases Kefir will unsubscribe appropriately by default I believe.
...or...
* no value or error is received from the source stream before a timeout. I think the natural idiom should be to take(1) from the source stream and combine this somehow with a Kefir.later(timeout) stream to define a timeout, but I can't figure out how to serve this through ```#toPromise()``` to satisfy its contract.

I may have missed the right combination to mediate between Kefir streams (which are three-valued event, error, end) and Promises (which are 'two-valued' success or failure) to provide timeout behavior. ```toPromise()``` only calls ```reject()``` in case the last item in the stream is an error, and offers no indication if the first event is an End. To work around this, I've tried and failed to use the existing API to trigger a Promise#reject() for stream end or timeout without implementing my own Promise handler (e.g. the API doesn't seem expressive enough to create a stream to satisfy toPromise(), even though Promises themselves are expressive enough for the case).

Understanding how to express this should perhaps have been the focus of my request in https://github.com/rpominov/kefir/issues/137

As a workaround I have this Gist, https://gist.github.com/cefn/c847bae4a5c372755498 which offers a promiseNextBefore signature, but seems very messy and explicitly imperative for such a simple scenario, as if there should be some declarative pathway to achieve this through the Kefir API. The equivalent of [endOnError](https://github.com/baconjs/bacon.js/#observable-endonerror-f) would be a step closer, but would also need some kind of way of triggering an error after a timeout, or triggering an error with a value (so Kefir#later could be used).

**Comment by rpominov** [comment]
> no value or error is received from the source stream before a timeout. I think the natural idiom should be to take(1) from the source stream and combine this somehow with a Kefir.later(timeout) stream to define a timeout, but I can't figure out how to serve this through #toPromise() to satisfy its contract.

Probably this is what you are looking for `Kefir.merge([sourse, Kefir.later(timeout)]).take(1).toPromise()`

**Comment by cefn** [comment]
Thanks for helping me think it through. 

However the problem with that implementation is that Promise gets sent an undefined value and this is considered a valid value rather than a rejection as it should for my application. Overloading the 'value channel' as in your example code is especially problematic if ```undefined``` is a valid value, which it actually is in some of my application's streams.

Is there any way to send an error instead in the two problem scenarios using the API (without something like the full-blown handler implementation I shared)? Handling a timeout and premature stream end as an error seems like the minimum needed for a networked service, so I can't be the only one with the requirement, surely. 

Without being able to serve an error (on timeout or end) through the Kefir transform API I can't trigger the ```reject()``` call of the Promise to ensure both my application logic and Kefir's tidyup. Your version has inspired me to come up with a hacky version but still pretty horrible and non-declarative...

```javascript
var failure = {};
Kefir.merge([source, Kefir.later(timeout, failure)]).take(1).toPromise().then(function(value){
    if(value===failure){ throw value; }else{ return value; };
})
```

API modifications which would resolve the issue would be toError() which could turn the Kefir.later() into an error, and endOnError() which would terminate the merged stream on the first error, therefore satisfying the contract of toPromise(). However, I may have overlooked an alternative way to achieve this.

Incidentally one form of signature which is used elsewhere is a [Deferred](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred), which exposes reject and resolve explicitly, and might answer some of your concerns in https://github.com/rpominov/kefir/issues/137 about the expressivity of Promises (not being able to cancel them). Allowing the programmer to force the fulfilment of the promise would then enable Kefir to free the subscribed resources.

**Comment by rpominov** [comment]
As I understand you want to convert some value-events to error-events. If so, you can do it using flatMap:

```
Kefir.later(timeout).flatMap(() => Kefir.constantError('Oops, timeout!'))
```

**Comment by cefn** [comment]
Converting value-events to error events is another relevant angle, but the interlocking limitations of signatures in the Kefir transform API (including the examples you've already shared) means I can't get coverage of the complete behaviour I require, even though it's fairly simple to express and quite a mainstream requirement I think. 

Take the suggestions you've shared so far. It's feasible to turn an event into an error with flatMap as you've shown, but doing this prevents the use of take(1) to force toPromise() to End, and then to resolve() or reject(). 

If you combine a constantError into a merge (i.e. combine your second suggestion with your first to try and construct the full behaviour), the Kefir#constantError() doesn't trigger an End at all, because merge doesn't end until its _last_ stream ends, (rather than the first stream), and the network stream is still running. Of course take(1) doesn't respond to errors, meaning you end up having to steer events through the value channel to trigger an end.

These sorts of dead ends have so-far prevented me from implementing the full behaviour using transforms. I have a working example as shown at the end, but it's more of a hacky way of 'bypassing' the Kefir API, sadly. 

Test cases are as follows; 

```javascript
var timeout = 1000;
var successSource = Kefir.interval(timeout * 0.5, "Hello World"); //success condition
var timeoutSource = Kefir.interval(timeout * 2.0, "Hello World"); //timeout condition
var endedSource = Kefir.interval(timeout * 0.5, "Hello World").takeUntilBy(Kefir.later(timeout * 0.25)); //premature end condition
```

...and an appropriate Kefir API transform chain should achieve the following...

* ```successSource``` should trigger toPromise() ***to be resolved*** with the received value
* ```timeoutSource``` should trigger toPromise() ***to be rejected*** with a timeout error
* ```endedSource``` should trigger toPromise() ***to be rejected*** with a stream-ended error

Having to overload the value channel, then separate the streamed values by using memory-equals like the implementation below seems hacky and suggests to me that there's something missing in the API, but perhaps you feel that this is the right approach.

```javascript
var timeoutToken = {};
var prematureToken = {};
function promiseNextBefore(source, timeout){
    return Kefir.merge([source.beforeEnd(function(){return prematureToken}), Kefir.later(timeout, timeoutToken)]).take(1).toPromise().then(function(value){
        if(value===timeoutToken){
            throw "Timed out while waiting for event";
        }
        else if(value===prematureToken){
            throw "Stream ended while waiting for event";
        }
        else{
            return value;
        }
    });
}
```

**Comment by rpominov** [comment]
Ok, I think this should work.

```
Kefir.merge([
  sourse,
  Kefir.later(timeout).flatMap(() => Kefir.constantError('Oops, timeout!'))
]).take(1).takeErrors(1).toPromise()
```

Btw, it would really helped me to understand problem and answer sooner if you've just wrote "But .take(1) won't work for errors" or something ;)

**Comment by cefn** [comment]
Thanks once again for considering the problem. Your suggestion was inspiring!

I remixed your code example so that it can differentiate the premature end condition, (the original code just waited, then threw a timeout error, instead of terminating early throwing a distinct 'premature end' error). 

Finally I have something which uses the Kefir API directly.

```javascript
    Kefir.merge([
        source.ignoreErrors(),
        source.ignoreValues().beforeEnd(function(){ return "Premature End"}).flatMap(Kefir.constantError),
        Kefir.later(timeout, "Timeout").flatMap(Kefir.constantError)
    ]).take(1).takeErrors(1).toPromise()
```

Here's the test cases again as a reminder...

```javascript
var timeout = 1000;
var successSource = Kefir.interval(timeout * 0.5, "Hello World"); //success condition
var endedSource = successSource.takeUntilBy(Kefir.later(timeout * 0.25)); //premature end condition 
var timeoutSource = Kefir.interval(timeout * 2.0, "Hello World"); //timeout condition
```

One of the reasons for not expressing it in terms of take(1) won't work for errors is that I've tried to approach the problem from lots of different directions, and in multiple different cases hit a dead end because of some dimension of the API contract but in each case it was different. I'm not sure I could say what I was missing, but rather that I was missing a stepping stone whichever route I took. 

For example you could articulate the problem as "terminate merge on first stream end" or equally, "Promise never fulfilled on stream end" depending what strategy I was hoping to attempt, and which particular dead end I hit. I was fundamentally approaching it from the wrong direction. Seemed like I could always get some part of it to work, but never all the parts at once, (except using the hack I previously shared).

I'm now relying on the ignoreXXX() signatures too, so updating to the latest version helped there.

Indeed learning that take(1) and takeErrors(1) can be employed in series is a useful learning point for me and combining this with the use of constantError as a 'map' is really neat and resolves the issue altogether.
