### ISSUE TITLE
takeNth?

### ISSUE THREAD

**Issue by elsehow** [rpominov/kefir#161]
Hi!

I've written a small wrapper to [take every nth value](https://github.com/elsehow/kefir-takenth) of a Kefir stream. I have no idea if my solution is eloquent, but would there be any interest in integrating this feature into Kefir?

**Comment by rpominov** [comment]
Hey!

Not sure, I've personally never needed this. I'd like to see what others think.
What is your use case, btw? What do you need it for?

Btw, I'd implement it a bit easier:

```js
function takeNth (stream, n) {
  let count = 0
  return stream.filter(() => {
    count++
    return count % n == 0
  })
}
```

This method is inevitably stateful so it's ok to store some state in a closure variable.

**Comment by elsehow** [comment]
Nice solution! I've updated my package.

My use case is taking buffers of EEG data flowing over a serial port:

```javascript
serialData.slidingWindow(512,512).takeNth(512).map(fft)
```

**Comment by rpominov** [comment]
I see. `.slidingWindow(512,512).takeNth(512)` probably could be replaced with `.bufferWithCount(512)` [if we'd have `bufferWithCount`](https://github.com/rpominov/kefir/issues/132).

**Comment by elsehow** [comment]
Agreed. I'll try to work on those and maybe issue a PR. Thanks

**Comment by rpominov** [comment]
:+1:
