### ISSUE TITLE
Property loses current value for pool.toProperty.flatMap.map

### ISSUE THREAD

**Issue by aindlq** [rpominov/kefir#162]
I'm using latest stable version - 3.1.0.

```javascript
const pool = Kefir.pool();
const property = pool.toProperty();
pool.plug(Kefir.constant(1));
property.log(); //[pool.toProperty] <value:current> 1

const property2 = property.flatMap(v => Kefir.constant(v + 1));
property2.log();//[pool.toProperty.flatMap] <value:current> 2

const property3 = property2.map(v => v + 1);
property3.log();//nothing
```

**Comment by iofjuupasli** [comment]
`flatMap` returns stream, not property

**Comment by rpominov** [comment]
Yeah, @iofjuupasli is right. You can convert it to a property like this:
```js
const property2 = property.flatMap(v => Kefir.constant(v + 1)).toProperty();
```

**Comment by aindlq** [comment]
What is the reason to not preserve observable type for flatMap?

**Comment by rpominov** [comment]
Frankly I can't remember the original reasoning. But I think we should leave it as is so people won't have to migrate.

Although we should fix the docs, now it didn't mentioned that flatMap always return a stream.
