### ISSUE TITLE
Equivalent to Subject

### ISSUE THREAD

**Issue by askmatey** [rpominov/kefir#165]
> The [`Subject`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md) class inherits both [`Observable`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md) and [`Observer`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observer.md), in the sense that it is both an observer and an observable. 
> 
> You can use a subject to **subscribe all the observers**, and *then* subscribe the subject to a **backend data source**. In this way, the subject can act as a *proxy* for a group of subscribers and a source.

See [RxJS Subjects](https://raw.githubusercontent.com/Reactive-Extensions/RxJS/master/doc/gettingstarted/subjects.md)

I am looking for alternatives to achieve the same functionality with Kefir. Is this somehow possible?

**Comment by rpominov** [comment]
No, we had something similar to it called Emitter-stream, which had Stream and [Emitter](http://rpominov.github.io/kefir/#emitter-object) interfaces. But it [was considered a bad pattern and removed](https://github.com/rpominov/kefir/issues/88) (the tldr; of that tread is "emitter is imperative pattern, but we want to do things in functional/declarative manner; in 90% of emitter usage cases it can be replaced with some declarative pattern, and lack of emitter should help people find that patterns; in the remaining 10% one can [extract](https://github.com/rpominov/kefir/issues/88#issuecomment-92512136) emitter from `Kefir.stream(emitter => ...)`")

**Comment by askmatey** [comment]
Sounds legit man.

Simplifying and rewriting my code without using declarative/functional patterns has helped me optimize my application. Thank you.

**Comment by antonioaguilar** [comment]
Subjects in the RxJS world seem to used for range of use cases. I'm just curious as to how you would implement the use of Subjects in KefirJS - what pattern would you instead recommend to use to subscribe and publish to a Stream at the same time?

**Comment by mAAdhaTTah** [comment]
I use `Kefir.stream` to solve the problem 90% of the time. There are a very small set of a problems I require something like a Subject, mostly in framework code. Some more details about what you're trying to do specifically could help me assist here.

**Comment by AgentME** [comment]
(Oh, the link in @rpominov's post was broken. I've edited his reply to fix it.)
