### ISSUE TITLE
filterBy activation

### ISSUE THREAD

**Issue by iofjuupasli** [rpominov/kefir#167]
```js
var Kefir = require("kefir");
var a = Kefir.sequentially(1000, [1, 2, 3]);
var b = Kefir.sequentially(1000, [false, false, false]);
a.filterBy(b).log();
console.log(a._active); // true
```

Seems that `a` shouldn't be active until `b` is truthy

**Comment by rpominov** [comment]
Yeah, you're probably right. And same for `skipUntilBy`. 

Also marking this as [breaking] because this change may potentially break peoples code.

**Comment by iofjuupasli** [comment]
Does it means, that in case `a.filterBy(b)` errors from `a` will not [flow](https://github.com/rpominov/kefir/blob/master/test/specs/filter-by.coffee#L9)?

**Comment by rpominov** [comment]
Hm, yes. I'm not sure which behavior is better here then.

**Comment by iofjuupasli** [comment]
`should be ended if primary was ended` also can't be implemented. Only when secondary is truthy.

My case for deactivation - I have [external process](https://www.npmjs.com/package/kefir-child-process) which is represented as endless `stream`. It starts external process in stream declaration, and ends it using callback in stream declaration for deactivation.
It's important to have child process only when application needs it, listen to it.
There is another observable which declare whether this stream required now.

So for my case:

```js
a$.flatMapLatest(a => a ? external$ : Kefir.never())
```

And it works ok for me. Its behavior almost same as `external$.filterBy(a$)` except things discussed here.


So we can leave `filterBy` as is for cases when 'errors' and 'end' are important, and it's ok that primary activated.

**Comment by rpominov** [comment]
Sounds good to me. I'll close this then, and we can revisit this later.
