### ISSUE TITLE
.log() activation

### ISSUE THREAD

**Issue by iofjuupasli** [rpominov/kefir#173]
I think there is two use of `.log`:
1. as output. So when we `.log` stream, it should be activated to perform tasks and output results to console
2. for debugging (through logging, but anyway). It shouldn't touch anything, and shouldn't activate stream, just log values when they are pass through

Almost always log is used for logging for debug purposes. And if activation\deactivation matters, after removing logging, or adding logging for debugging somewhere on deactivated stream, it starts to behave differently than before logging.

I think, It will be very useful to have a passive `.log`

**Comment by jensklose** [comment]
+1

**Comment by rpominov** [comment]
Hm, I think Bacon has something similar as an undocumented method `Bacon.spy(obs)`, I don't know much about it though (since it undocumented). Would be cool if someone could investigate how it works in Bacon, and in other libs if they have similar features.

How do you think it should work? There is at lest two options:

```js
// 1. Return a new observable.
//    Basically `obs.map(console.log)`, but with output like in `obs.log()`
const newObs = obs.spy();
newObs.onValue();

// 2. Just spies on an observable, 
//    allowing us to work with same obs instance in the rest of the code
obs.spy();
obs.onValue();
```

First one probably much easier to implement.

Not sure yet if we should add this, although don't see strong reasons why not.

**Comment by iofjuupasli** [comment]
The first as I understand can be implemented using `withHandler` which reemits all events.

#147 
Now `withHandler` on property returns stream. It's the only problem I see with this approach.

If it will return observable of same type, I think there is no difference for user whether it's the same object or another with same behavior

**Comment by AlexGalays** [comment]
Just got bitten by this; Had no idea log() would activate a Property and make the subsequent onValue not trigger immediately.

**Comment by jeron-diovis** [comment]
+1 for this issue. `log` is a debugging tool, but it easily creates new bugs itself. It's so painful.

**Comment by rpominov** [comment]
Anyone want to create a PR with `spy()` method?

**Comment by polytypic** [comment]
It is called [doLog](https://github.com/baconjs/bacon.js/#observable-dolog) in Bacon.

**Comment by mAAdhaTTah** [comment]
`spy` landed, so closing this one.
