### ISSUE TITLE
documentation request - differences with bacon / RxJS

### ISSUE THREAD

**Issue by dcsan** [rpominov/kefir#175]
as someone researching which library to use, it would be great to have some info in the README as to how this compares to Bacon and RxJS. 

I understand performance is a goal, but is there any benchmark compares to RxJS?
How about use of ES6 methods?

For anyone else passing by Googling turned up a few points but more bacon/rxjs than kefir.

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=bacon%20rxjs%20kefir&es_th=1

http://stackoverflow.com/questions/25734019/which-actual-products-web-mobile-apps-etc-use-bacon-js
https://forums.manning.com/posts/list/35274.page#p98857

**Comment by rpominov** [comment]
Perhaps this might help https://github.com/rpominov/kefir/blob/master/bacon-vs-kefir-api.md (it's quite outdated though). As for benchmarks you can take a look at https://github.com/cujojs/most/tree/master/test/perf . This is probably all I have, maybe someone could share more links here.

Closing as I don't think this can be completely resolved, but feel free to continue discussion.

**Comment by dcsan** [comment]
great, thanks for the links!
