### ISSUE TITLE
Deprecations warnings disable API is broken

### ISSUE THREAD

**Issue by rpominov** [rpominov/kefir#185]
After we switched to Rollup, we've accidentally broken the warnings disabling feature. It worked like this:

```
const kefir = require('kefir')
Kefir.DEPRECATION_WARNINGS = false
```

Not sure if this API can be preserved with Rollup, maybe we'll need to switch to something like the following in order to fix this:

```
const kefir = require('kefir')
Kefir.disableDeprecationWarnings()
Kefir.enableDeprecationWarnings()
```

**Comment by rvikmanis** [comment]
Hope this is not super critical, can do it probably next week.

**Comment by rpominov** [comment]
Thanks, @rvikmanis. That would be cool. Not critical at all as it seems to me.
