### ISSUE TITLE
question: how to "end" a fromEvents stream

### ISSUE THREAD

**Issue by boneskull** [rpominov/kefir#187]
(Sorry for spamming with questions)

I have a stream created via `fromEvents()` which will at some point no longer be useful.  I'd like to clean it up.  How can I cause this stream to end?  `stream._emit('end')` exists, but this is obviously not a public API.

**Comment by boneskull** [comment]
It appears fromEvents() will return a function which stops listening.  I'll change this issue to reflect that in the docs

**Comment by boneskull** [comment]
ok, it appears that `fromEvents()` will unsubscribe upon deactivation.  But I'm having a tough time understanding what deactivation looks like.

**Comment by rpominov** [comment]
Yeah, you don't have to end each stream in order to it be garbage collected.

```js
var foo = Kefir.fromEvents(target, 'foo')
foo.onValue(fn)

// now if we want to dispose all resources, all we need to do is:
foo.offValue(fn)
foo = null 
```

> But I'm having a tough time understanding what deactivation looks like.

Did you read this section in the docs? http://rpominov.github.io/kefir/#active-state

**Comment by boneskull** [comment]
@rpominov Yes...many times, unfortunately.  Perhaps that section needs more clarification.  I get it now, thanks.
