### ISSUE TITLE
Unify signatures of static and instance combination methods?

### ISSUE THREAD

**Issue by jeron-diovis** [rpominov/kefir#190]
> Kefir.combine(obss, [passiveObss], [combinator])

but

> obs.combine(otherObs, [combinator])

So, if I want to combine more than two streams at once, I need to use only "static" version of `combine`.
Same for all combination methods.

Is this intentional, or we can make instance methods to behave same as static ones?

---

Also, doc shows example `Kefir.combine([a, b], (a, b) => a + b);`, but on practice it seems to work as `Kefir.combine([a, b], ([ a, b ]) => a + b);` (combinator receives an array). Is it error in doc?

**Comment by rpominov** [comment]
Yeah, this was intentional. The logic is you either do `combine(many)` or `combine(one + one)`, `combine(one + many)` seems kind of wrong to me.

Not sure if that makes sense, but I would't introduce a braking change like that for no strong reason.

---------------------

I tried the first example in console, seems fine:

![image](https://cloud.githubusercontent.com/assets/825702/13610813/87dbb590-e570-11e5-851a-d4c9cd03747d.png)

**Comment by jeron-diovis** [comment]
> I tried the first example in console, seems fine

Yep, I "tested" in wrong way, I'm sorry. 

---

> The logic is you either do combine(many) or combine(one + one), combine(one + many) seems kind of wrong to me.

Not sure there is something wrong in doing `combine(one + many)`... Just combine streams, what's the difference how much of them there? 
In fact, currently it makes sense to use only static methods everywhere, because the need to always keep in mind which version of API is allowed to be used in each concrete case looks like nonsense. 

Anyway,

> I would't introduce a braking change like that for no strong reason

Is this a breaking change? Besides `passiveObss` param, the only thing is required to do is this:
```js
Observable.prototype.combine = function(other, combinator) {
  return combine([this].concat(other), combinator);
};
```
Am I wrong?

**Comment by rpominov** [comment]
So you suggesting support `Observable | Array<Observable>` as the first argument? I'm not a big fun of such unnecessary polymorphisms to be honest. IMO, the less polymorphic the API the easier to read the code. For example we see `foo.combine(bar)` somewhere in the code, the question is what is `bar`? Is it array or an Observable?

> Not sure there is something wrong in doing `combine(one + many)`

Sorry, it's probably just my intuition, it's just _feels_ wrong to have that in API.

**Comment by rpominov** [comment]
Also we have plans to support objects in static combine https://github.com/rpominov/kefir/issues/143, which may add more confusion in instance combine method if we add arrays support in it.

**Comment by jeron-diovis** [comment]
> the less polymorphic the API the easier to read the code. For example we see foo.combine(bar) somewhere in the code, the question is what is bar? Is it array or an Observable?

Although in general I agreed, IMO the API consistence is more important than potential readability problems. After all, it's programmer's responsibility to keep his code readable.

> Also we have plans to support objects in static combine #143 

...and then instance methods will become even more useless?)

But ok, this is reasonable. With objects support, it will be impossible to provide a named key for instance on which `combine` was called, yes?

**Comment by rpominov** [comment]
> ...and then instance methods will become even more useless?)

Probably, I tend to always use static alternative if there is one to be honest :)

> But ok, this is reasonable. With objects support, it will be impossible to provide a named key for instance on which combine was called, yes?

Yep.

**Comment by jeron-diovis** [comment]
Understood. I prefer an opposite approach. Less coupling, as for me, easier to mock, etc.
But, your game – your rules :) Anyway your lib looks much more preferable for me in comparison with alternatives.

If you allow, one more question, besides the topic.
If I need a stream to which I want push events imperatively, from outside – is this a correct approach?
```js
var dispatch;
var stream = Kefir.stream(emitter => dispatch = emitter.emit);
...
dispatch(...);
```
Or just call `stream._emitValue(...)` ? What is more proper way?

**Comment by rpominov** [comment]
The first one with `dispatch` is more correct.

We had `Kefir.emitter()` before, it worked like this:

```js
const em = Kefir.emitter()
em.map(x = > x + 1).onValue(...)
em.emit(1)
```

But people new to FRP tend to abuse this imperative API, for instance:

```js
// wrong
const streamB = Kefir.emitter()
streamA.onValue(x => streamB.emit(x + 1))

// right
const streamB = streamA.map(x => x + 1)
```

So we decided to remove it from API, here is the original discussion #88

**Comment by jeron-diovis** [comment]
> Also, although it looks more complicated with .fromBinder, now it more obvious what really happening under the hood, and if a developer write that code it means that he or she understand what going on. And it will be more obvious for other people who will read it.

:+1: Great

Thanks for your replies very much.
