### ISSUE TITLE
Autobind Stream Instance Methods?

### ISSUE THREAD

**Issue by mAAdhaTTah** [rpominov/kefir#204]
In the emitter section, it explains that the emitter's `emit` method(s) are autobound to the instance so they can be passed in. Is it possible to have a stream's methods bound to its instance as well?

In my case, I'm trying to do something like this:

```js
const stream = Kefir.pool();
events.map(event => fromEvents(event.el, event.type))
  .forEach(stream.plug);
```

But the `plug` call fails because `this._add` does not exist because the `this` isn't bound correctly. I'm doing `forEach(stream.plug.bind(stream))` for now, but that always feels a little ugly.

Thoughts?

**Comment by rpominov** [comment]
This will be pretty expensive in terms of memory usage per each Stream instance.

**Comment by mAAdhaTTah** [comment]
Fair enough. I'll stick with `stream.plug.bind(stream)` method then. Thanks!
