### ISSUE TITLE
Only the first stream is created when trying to create multiple streams

### ISSUE THREAD

**Issue by kevinbarabash** [rpominov/kefir#205]
```js
const streamA = Kefir.stream(emitter => this.emitterA = emitter);
const streamB = Kefir.stream(emitter => this.emitterB = emitter);
```

Only the `this.emitterA` gets set.  I put a breakpoint inside both callbacks to `Kefir.stream`, but only the first gets called.  My expectation is that both would get called.

**Comment by rpominov** [comment]
Do you subscribe to both streams? The callback that you're passing to `Kefir.stream()` is called when stream gets the first subscriber. With this code alone none will be called actually.

**Comment by kevinbarabash** [comment]
That was the problem.  Thanks for the quick response.  Also, kefir is awesome.  I always wanted to use frp, but I couldn't justify the size of rxjs.
