### ISSUE TITLE
API compatibility with RxJS

### ISSUE THREAD

**Issue by antonioaguilar** [rpominov/kefir#206]
I'm using KefirJS in a new project mostly because it has a smaller API than RxJS but to what extent is KefirJS compatible with RxJS?. For example, are there any major differences between [Rx.Observable.prototype.scan(accumulator, [seed])](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/scan.md) and KefirJS [scan](https://rpominov.github.io/kefir/#scan)? From a quick look at the docs, they seem to be compatible but perhaps you can clarify if there are any differences. Thanks.

**Comment by rpominov** [comment]
Sorry, I'm not an RxJS. So can't answer that unfortunately. Closing to cleanup open issues.
