### ISSUE TITLE
Are there any browser compatibility info for kefir?

### ISSUE THREAD

**Issue by CicholGricenchos** [rpominov/kefir#216]
Hi rpominov,

I've checked the docs but didn't find any description about browser compatibility. With what requirement kefir is expected to work? If there are any known requirement, adding them to the README would be very helpful.

Thanks!

**Comment by rpominov** [comment]
We had to drop IE8 support recently, to implement [ES Observables](https://github.com/tc39/proposal-observable) compatibility properly. Other than that we should support pretty much everything.

**Comment by CicholGricenchos** [comment]
I was exactly just wondering if kefir can support IE8. 
By the way, why not add these statement to README? Would be very much appreciated.

**Comment by rpominov** [comment]
Added it to readme, thanks for the suggestion.
