### ISSUE TITLE
General pattern for async map ?

### ISSUE THREAD

**Issue by niahoo** [rpominov/kefir#220]
Hi, 

What is the standard way to achieve this:

`stream.mapAsync((val, next) => xhr({data: val, success: next})).map(doStuff)`

So `success` is `serverData => next(serverData)`, next continues the stream and doStuff is called only when the ajaxRequest is complete. I read about `withHandler` but I may have missed a simpler solution.

Or is it an anti-pattern ?

Thank you.

**Comment by mAAdhaTTah** [comment]
Use [`flatMap`](http://rpominov.github.io/kefir/#flat-map).

**Comment by niahoo** [comment]
Hi, thanks. I was trying something before you edit

```js
let poll = (value, callback) => setTimeout(() => callback(value + 1), 100)

K.sequentially(1000, [1, 2, 3])
	.flatMap(x => K.fromCallback(next => poll(x, next)))
	.log()

```

And it works as intended :

```
[sequentially.flatMap] <value> 2
[sequentially.flatMap] <value> 3
[sequentially.flatMap] <value> 4
[sequentially.flatMap] <end>
```

As I need to emit only once per value, I think it is equivalent to the `stream` version.

I will try with a Promise version, good idea.

Thank you :)

**Comment by rpominov** [comment]
Yea, flatMap is the most idiomatic way to go in this case.

**Comment by niahoo** [comment]
Ok thank you.
