### ISSUE TITLE
can't access fromEvents when using es6 imports

### ISSUE THREAD

**Issue by micahscopes** [rpominov/kefir#223]
```javascript
import { fromEvents } from 'kefir'
```

gives me `Export 'fromEvents' is not defined by '.../node_modules/kefir/dist/kefir.js'`

Just to see what'd happen, I tried doing:
```javascript
import * as kefir from 'kefir'

kefir.fromEvents(...)
```
and that just resulted in `kefir.fromEvents` being undefined.

**Comment by rpominov** [comment]
Does it work for other methods? For example `import {create} from 'kefir'`?

**Comment by micahscopes** [comment]
yeah, I tried it with `stream` and that worked.

**Comment by rpominov** [comment]
I tried it with `rollup` and it doesn't work with any method. Not sure if it should actually, maybe `rollup` doesn't support this kind of imports from a cjs module. `import Kefir from 'kefir'` works fine in my setup though.

Are you sure it works for other methods, and what bundler do you use webpack/rollup/browserify?

**Comment by micahscopes** [comment]
ahh, just realized I'm using the rollup-plugin-commonjs plugin. that definitely explains why it did anything at all.  I just need to figure out the correct way of importing.

so I'll try `import Kefir from 'kefir'`

thanks

**Comment by rpominov** [comment]
Ok, I'll close this for now then.
