### ISSUE TITLE
Convert Pool to Stream?

### ISSUE THREAD

**Issue by mAAdhaTTah** [rpominov/kefir#239]
I have a Pool that I need to use to plug, and I want to pass that Pool into a user-defined function, but I don't want that function to be able to `plug` into that Pool. Is there a preferred way to cut off that functionality?

**Comment by rpominov** [comment]
Hi! `pool.changes()` should do the trick, except it will also ignore [current values](http://rpominov.github.io/kefir/#current-in-streams) from the pool. So if you, for example, want to add `Kefir.constant()`'s to the pool _before_ you subscribe to it, you should convert it to a property instead using `pool.toProperty()`.

**Comment by mAAdhaTTah** [comment]
Perfect, that should do it. Thanks!
