### ISSUE TITLE
Analog for RxJS do?

### ISSUE THREAD

**Issue by johnwheeler** [rpominov/kefir#241]
Is there a Kefir analog to RxJS `do`? I'm trying to invoke an arbitrary action after returning from `.map`

Edit: Here is the docs for `do`

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/do.md

Thanks

**Comment by rpominov** [comment]
Hey! `obs.map((x) => {action(); return x})` should do the trick.

**Comment by johnwheeler** [comment]
Thanks @rpominov. This might be a dumb question, but is there a way to do an arbitrary action *after* a value is returned from a stream if you don't have API access to the observer?

For example, I'm using a third-party library with a method like this

`row.addButton(someStream)`

The `row` is the observer of the stream, but it doesn't have any events such as `afterButtonAdded`

**Comment by rpominov** [comment]
Sorry, I don't understand. Could you perhaps show how you would it using Rx, or elaborate more?

**Comment by johnwheeler** [comment]
This code:

```
const source = Rx.Observable.of(1,2,3,4,5);
//transparently log values from source with 'do'
const example = source
  .do(val => console.log(`BEFORE MAP: ${val}`))
  .map(val => val + 10)
  .do(val => console.log(`AFTER MAP: ${val}`));
//'do' does not transform values
//output: 11...12...13...14...15
const subscribe = example.subscribe(val => console.log(val));
```

taken from this page: https://www.learnrxjs.io/operators/utility/do.html

Is it possible to accomplish the last `do` in the chain that prints `AFTER MAP...`?

**Comment by rpominov** [comment]
Sure, instead the first `do` you could write `map(val => {console.log(...);
return val})` and so on. The key is that we return the same value from the
fuction after we perform a side effect, so it works like `do`.

вт, 2 мая 2017 г. в 19:41, John Wheeler <notifications@github.com>:

**Comment by johnwheeler** [comment]
Sorry, I don't mean to be a PITA, but I'm interested in the **last** do in the example, not the first. Once `.map` returns a value, nothing can be done afterwards of course (e.g. can't do this...)

```
map(val => { return val; console.log(...) })
```

Yet the RxJS example effectively does that. I'm wondering if there is a way to accomplish the same with Kefir.

**Comment by mAAdhaTTah** [comment]
@johnwheeler I've done similar things using `flatMap` and creating a stream to do this:

```js
someObservable$.flatMap(val => Kefir.stream(emitter => {
  emitter.value(val);
  performSideEffect();
  emitter.end();
});
```

I like it because the `flatMap` & use of the stream also makes it clearer that a side effect is happening here.

**Comment by spro** [comment]
Are you looking for onValue?

**Comment by rpominov** [comment]
I still don't understand what the issue is. Here is the full example:

```js
const source = Kefir.sequentially(0, [1, 2, 3]);;
//transparently log values from source with 'do'
const example = source
  .map(val => {console.log(`BEFORE MAP: ${val}`); return val})
  .map(val => val + 10)
  .map(val => {console.log(`AFTER MAP: ${val}`); return val});
//'do' does not transform values
//output: 11...12...13...14...15
const subscribe = example.observe(val => console.log(val));
```
