### ISSUE TITLE
Flow 0.50.0 throws errors in kefir

### ISSUE THREAD

**Issue by EvHaus** [rpominov/kefir#245]
After upgrading to Flow 0.50.0 I am now getting the following Flow errors coming from `kefir`:

```
node_modules/kefir/dist/kefir.js.flow:40
 40:     next?: (value: V) => any,
                        ^ V. invariant position (expected `V` to occur only covariantly)

node_modules/kefir/dist/kefir.js.flow:41
 41:     error?: (error: E) => any,
                         ^ E. invariant position (expected `E` to occur only covariantly)

node_modules/kefir/kefir.js.flow:40
 40:     next?: (value: V) => any,
                        ^ V. invariant position (expected `V` to occur only covariantly)

node_modules/kefir/kefir.js.flow:41
 41:     error?: (error: E) => any,
                         ^ E. invariant position (expected `E` to occur only covariantly)
```

**Comment by mAAdhaTTah** [comment]
There are two articles about this on Flowtype that should help here:

https://flow.org/en/docs/lang/variance/
https://flow.org/en/docs/lang/depth-subtyping/

I _think_ the functions may just need to add `+` to the generics passed into them.

**Comment by rpominov** [comment]
I have a fix in #246 , but not sure if it's correct. As far as I understand Flow thinks that this code is unsafe because `subscribe()` may mutate passed object, and I've tricked Flow to think that It's allright using interface.

See also #2354

/cc @hallettj @AgentME

**Comment by AgentME** [comment]
Yeahh variance errors are fun. I think that pull request looks right.

**Comment by rpominov** [comment]
Ok, probably should merge it.
