### ISSUE TITLE
Stream from promise does not handle exceptions properly

### ISSUE THREAD

**Issue by mehtonen-boox** [rpominov/kefir#248]
Seems like errors are swallowed when stream is created out of promise. Also **onError** handler does not work properly. Am I misusing library or is it a bug?

```
const stream = kefir.fromPromise(Promise.resolve())
  .map(e => {
    throw new Error('This error is swallowed');
  });

stream.onValue(() => {
  console.log('onValue is not invoked');
});

stream.onError(() => {
  console.log('onError is not invoked');
});
```

**Comment by mehtonen-boox** [comment]
Nevermind. It was issue with https://limonte.github.io/sweetalert2/ which extends Promise prototype with done method.

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
