### ISSUE TITLE
Write access to repository

### ISSUE THREAD

**Issue by rpominov** [rpominov/kefir#254]
@mAAdhaTTah @AgentME @hallettj @rvikmanis

Hi all! I want to thank you all for great contributions to this project in the past, and give you write access. This way this project may continue to improve without me. No worries, I'll still be around. But feel free to merge PRs and make decision without me. I think we can make a simple rule: if two of us or more (including author) approve a PR, and no one disapprove, it should be merged.

Also feel free to just ignore this if you don't want to participate, no pressure :)

**Comment by AgentME** [comment]
I'm game!

**Comment by rpominov** [comment]
@AgentME Great to have you on board :)

**Comment by mAAdhaTTah** [comment]
I'm in as well, although I don't see the email invite mentioned in #252. Can you resend?

**Comment by rpominov** [comment]
@mAAdhaTTah Try this link https://github.com/rpominov/kefir/invitations , if I got it right you should be able to accept invite there.

**Comment by mAAdhaTTah** [comment]
Oh hey that works. I'm in!

**Comment by rpominov** [comment]
@rvikmanis Not sure if you got a notification, because I incidentally did't mention you in original message and then edited it. So mentioning again just in case.

Don't know what to do with this issue, probably should just close it.

**Comment by rvikmanis** [comment]
I am also in.

**Comment by rpominov** [comment]
Hi all! What do you think about transferring this repo to https://github.com/kefirjs ?

@mAAdhaTTah We could transfer `chai-kefir` there as well, if you want.

**Comment by rpominov** [comment]
Also does anyone want to make actual work of transferring it? :)
We'll need to make sure that documentation site still works etc.
I'll give all necessary access of course.

**Comment by rvikmanis** [comment]
I can do it today.

**Comment by rpominov** [comment]
Great! Let's do it! 
I'll add all collaborator to the organization and make you owner of this repo.

I think github automatically creates redirects for transferred repos, but it doesn't do it for the websites. I've had to leave a zombie repo behind when I was changing my login on GitHub https://github.com/pozadi/kefir . IIRC the only reason for this was to set up redirect for documentation website.

**Comment by rpominov** [comment]
> and make you owner of this repo

Seems like GitHub doesn't have this functionality... 
Nevermind, I'll do it by myself. Not that much work actually 😂

**Comment by rvikmanis** [comment]
Oh well :)

What do you think about `kefir.js.org`? Do we want?

**Comment by rpominov** [comment]
Ok, not sure I've updated links everywhere but we'll update them eventually when find them.
You should all get invites to the organization.

I don't have a strong opinion about `kefir.js.org` domain. But if you guys want it, I don't mind.

**Comment by mAAdhaTTah** [comment]
Right now, https//rpominov.github.io/kefir/ is correctly redirecting, although the Travis build is failing.

**Comment by mAAdhaTTah** [comment]
`chai-kefir` has now been transferred into the organization as well.

**Comment by rpominov** [comment]
Travis seems to assume that it's a ruby project for some reason. But I've only looked briefly so far.

**Comment by mAAdhaTTah** [comment]
Minor issue, but any idea why the favicon isn't working on the new URL?

**Comment by rpominov** [comment]
It used to work by accident, was taken from https://github.com/rpominov/rpominov.github.io .
